### ISSUE TITLE
Nested Navigator not working 

### ISSUE THREAD

**Issue by MarcHbb** [hoaphantn7604/react-native-curved-bottom-bar#16]
I have for each screen a stack navigator associated 
( FeedNavigator for exemple )

But it seems that it's not working 
Here is the error 

`Error: Another navigator is already registered for this container. You likely have multiple navigators under a single "NavigationContainer" or "Screen". Make sure each navigator is under a separate "Screen" container. See https://reactnavigation.org/docs/nesting-navigators for a guide on nesting.`

But when I replace by a single compoenent ( <FeedNavigator /> to <Feed /> ) it works, but cannot navigate throught to the next screen on the stack 

<img width="612" alt="Capture d’écran 2021-12-03 à 17 23 13" src="https://user-images.githubusercontent.com/15633836/144636904-46d1a369-65ce-492d-96c8-8def9973e19c.png">

**Comment by hoaphantn7604** [comment]
You cannot pass inside a stack of react-navigation. replace by a single component.
Using "const { navigate } = useNavigation()" to navigate inside

**Comment by nhoxx** [comment]
I have the same problem as you, but I don't have a solution, I hope someone can help me, thank you.

**Comment by hoaphantn7604** [comment]
https://github.com/hoaphantn7604/react-native-template-components
You can refer to the way that I navigate.

**Comment by buscanopaul** [comment]
Hi hoaphantn7604, Do you have unmountOnBlur options on the CurvedBottomBar.Screen? I want to reset the stack navigator every time I want to click the bottom icons.

Example:
` <CurvedBottomBar.Screen
                    name="Home"
                    position="left"
                    component={({ navigate }) => (
                        <HomeStackNavigator />
                    )}
                    // unmountOnBlur={true}
                    // options={{unmountOnBlur: true}}
                />`

**Comment by hoaphantn7604** [comment]
> Hi @hoaphantn7604, Do you have unmountOnBlur options on the CurvedBottomBar.Screen? I want to reset the stack navigator every time I want to click the bottom icons.
> 
> Example: ` <CurvedBottomBar.Screen name="Home" position="left" component={({ navigate }) => ( <HomeStackNavigator /> )} // unmountOnBlur={true} // options={{unmountOnBlur: true}} />`

Hi @buscanopaul,
Can you describe your request in more detail?

**Comment by buscanopaul** [comment]
Hi @hoaphantn7604, Thank you for your response.

My main issue was I can' reset the nested or go back to initial route stack navigator when I click again the bottom navigation icon (home). Please refer screenshot below

<img width="367" alt="Screen Shot 2021-12-08 at 4 06 43 PM" src="https://user-images.githubusercontent.com/17734014/145173286-b916fa1e-231b-4bb1-8116-090a9977cb6e.png">

In the screenshot Instead of click the back button to reset the nested stack navigator. I want to reset it when I click the home icon again. Just like the default react navigation bottom tab behavior.

Here's my app.js
`    <NavigationContainer>
      <TabNavigator />
    </NavigationContainer>`

In my TabNavigator.js. I'm just using the Example 1 template just replace View with my stack navigator component
`<CurvedBottomBar.Screen
                    name="Home"
                    position="left"
                    component={({ navigate }) => (
                        <HomeStackNavigator />
                    )}
               />`

My HomeStackNavigator.js
`<Stack.Screen name="Home" component={HomeScreen} />`
`<Stack.Screen name="Transactions" component={TransactionsScreen} />`


I hope you understand. Thank you

**Comment by hoaphantn7604** [comment]
hi @buscanopaul ,
You can refer to Ex:
```js
import React, { useImperativeHandle } from 'react';
import { View } from 'react-native';
import { styles } from './styles';

export const HomeScreen = React.forwardRef((props, ref) => {
  useImperativeHandle(ref, () => {
    return { reload: reload };
  });

  const reload = () => {
    // Events
  };

  return <View style={styles.main} />;
});
```
You get curentRef then call reload function.

**Comment by yugg98** [comment]
Cant add more than 3 CurvedBottomBar.Screen

**Comment by hoaphantn7604** [comment]
This issue has been resolved in version 2.0.0.

**Comment by KarthiKeyan05046** [comment]
@buscanopaul 
i want more detailed answer for  Instead of click the back button to reset the nested stack navigator. I want to reset it when I click the home icon again. Just like the default react navigation bottom tab behavior.
this is one of the issue i hassle to use this library but i love this library can you add default navigation behaviour reset the nested stack navigator thankyou

**Comment by MFoxx** [comment]
> @hoaphantn7604 Mr Admin! Kindly help me to solve the issue. i want more detailed answer for issue raised by @buscanopaul. Instead of click the back button to reset the nested stack navigator. I want to reset it when I click the home icon again. Just like the default react navigation bottom tab behavior. this is one of the issue i hassle to use this library but i love this library can you add default navigation behaviour reset the nested stack navigator thankyou

Hi, have you managed to fix this, or find a workaround ?

**Comment by KarthiKeyan05046** [comment]
Thankyou for your reply, I am not fix anything.Can you fix this issue?
